[build-dependencies]
tonic-build.workspace = true
tonic-prost-build.workspace = true

[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[package]
name = "api"
edition.workspace = true
version.workspace = true
